name: pr_build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    env:
      R_CHECK_DONTTEST_EXAMPLES: false
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: |
          install.packages(c('rmarkdown', 'styler','usethis', 'devtools', 'pkgdown', 'rcmdcheck', 'remotes'))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Configure git
        run: |
          git config --local user.email "noreply@github.com"
          git config --local user.name "GitHub"
      - name: Check
        run: |
          Rscript -e 'devtools::check()'
          git add man/ NAMESPACE
          git commit \
          --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
          -m 'ðŸ“š Render Roxygen documentation' || echo "No changes to commit"
      - name: Style
        run: |
          Rscript -e 'usethis::use_tidy_style()'
          git add .
          git commit \
          --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
          -m 'ðŸŽ¨ Style R code' || echo "No changes to commit"
      - name: Render README
        run: |
          Rscript -e 'devtools::build_readme()'
          git add README.md
          git commit \
          --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
          -m 'ðŸ“„ Render README.Rmd' || echo "No changes to commit"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
      - name: Docs
        run: |
          Rscript -e "pkgdown::build_reference(); devtools::build_site()"
          git add docs
          git commit \
          --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
          -m "ðŸ“‘ Build docs site" || echo "No changes to commit"
      - name: Push final
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
